function [fitresult, gof] = createFit(stopping, crossSec)
%CREATEFIT(STOPPING,CROSSSEC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : stopping
%      Y Output: crossSec
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Mar-2016 22:16:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( stopping, crossSec );

% Set up fittype and options.
ft = fittype( 'C*(1-exp(-((x-L)/w)^s))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0003 1 1 2];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'crossSec vs. stopping', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel stopping
ylabel crossSec
grid on


